### ISSUE TITLE
Unknown groups in update groups config - stats 2.0.0.

### ISSUE THREAD

**Issue by InoMurko** [blockscout/blockscout-rs#1059]
```
2024-09-17T13:33:33.111069Z ERROR stats_server: service failed with error: Unknown groups in update groups config: ["NewContracts", "NewTxns", "CompletedTxns", "ActiveAccounts", "NewVerifiedContracts", "TotalBlocks", "TotalAddresses"]
Error: Unknown groups in update groups config: ["NewContracts", "NewTxns", "CompletedTxns", "ActiveAccounts", "NewVerifiedContracts", "TotalBlocks", "TotalAddresses"]
```

```
   STATS_UPDATE_GROUPS__SCHEDULES__TOTAL_BLOCKS: "0 0 */1 * * * *"
   STATS_UPDATE_GROUPS__SCHEDULES__ACTIVE_ACCOUNTS: "0 2 */1 * * * *"
   STATS_UPDATE_GROUPS__SCHEDULES__COMPLETED_TXNS: "0 5 */1 * * * *"
   STATS_UPDATE_GROUPS__SCHEDULES__TOTAL_ADDRESSES: "0 7 */1 * * * *"
   STATS_UPDATE_GROUPS__SCHEDULES__NEW_TXNS: "0 10 */1 * * * *"
   STATS_UPDATE_GROUPS__SCHEDULES__NEW_CONTRACTS: "0 15 */1 * * * *"
   STATS_UPDATE_GROUPS__SCHEDULES__NEW_VERIFIED_CONTRACTS: "0 30 */1 * * * *"
```

other envs set:
```
  STATS__DB_URL: 
  STATS__BLOCKSCOUT_DB_URL: 
  STATS__CREATE_DATABASE: "true"
  STATS__RUN_MIGRATIONS: "true"
  STATS__SERVER__HTTP__ENABLED: "true"
  STATS__SERVER__HTTP__ADDR: "0.0.0.0:8081"
  STATS__SERVER__HTTP__MAX_BODY_SIZE: "2097152"
  RUST_BACKTRACE: "1"
  STATS_CHARTS__TEMPLATE_VALUES__NATIVE_COIN_SYMBOL: {{ .Values.COIN_TICKER | quote }}
```
