### ISSUE TITLE
Upgrade from 0.6.0 to 1.0.0

### ISSUE THREAD

**Issue by lucgerrits** [blockscout/blockscout-rs#390]
Using v0.6.0 works fine, but it won't work of course if using blockscout v5.1.1.

When upgrading from v0.6.0 to v1.0.0, I get the error:
```
thread 'main' panicked at 'failed to read config: unknown field `addr`, expected `http` or `grpc`', smart-contract-verifier-server/src/main.rs:5:36
```

I use the save config in both cases:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "main-node.fullname" . }}-sc-verifier-config
data: 
    SMART_CONTRACT_VERIFIER__SERVER__ADDR: "0.0.0.0:{{ .Values.scVerifier.port }}"

    # if omitted, number of CPU cores would be used
    #SMART_CONTRACT_VERIFIER__COMPILERS__MAX_THREADS: "8"
    
    SMART_CONTRACT_VERIFIER__SOLIDITY__ENABLED: "true"
    SMART_CONTRACT_VERIFIER__SOLIDITY__COMPILERS_DIR: "/tmp/solidity-compilers"
    SMART_CONTRACT_VERIFIER__SOLIDITY__REFRESH_VERSIONS_SCHEDULE: "0 0 * * * * *"

    # It depends on the OS you are running the service on
    SMART_CONTRACT_VERIFIER__SOLIDITY__FETCHER__LIST__LIST_URL: "https://solc-bin.ethereum.org/linux-amd64/list.json"
    #SMART_CONTRACT_VERIFIER__SOLIDITY__FETCHER__LIST__LIST_URL: "https://solc-bin.ethereum.org/macosx-amd64/list.json"
    #SMART_CONTRACT_VERIFIER__SOLIDITY__FETCHER__LIST__LIST_URL: "https://solc-bin.ethereum.org/windows-amd64/list.json"

    SMART_CONTRACT_VERIFIER__VYPER__ENABLED: "true"
    SMART_CONTRACT_VERIFIER__VYPER__COMPILERS_DIR: "/tmp/vyper-compilers"
    SMART_CONTRACT_VERIFIER__VYPER__REFRESH_VERSIONS_SCHEDULE: "0 0 * * * * *"

    # It depends on the OS you are running the service on
    SMART_CONTRACT_VERIFIER__VYPER__FETCHER__LIST__LIST_URL: "https://raw.githubusercontent.com/blockscout/solc-bin/main/vyper.list.json"
    #SMART_CONTRACT_VERIFIER__VYPER__FETCHER__LIST__LIST_URL: "https://raw.githubusercontent.com/blockscout/solc-bin/main/vyper.macos.list.json"

    ##SMART_CONTRACT_VERIFIER__SOLIDITY__FETCHER__S3__ACCESS_KEY: "access_key"
    ##SMART_CONTRACT_VERIFIER__SOLIDITY__FETCHER__S3__SECRET_KEY: "secret_key"
    ##SMART_CONTRACT_VERIFIER__SOLIDITY__FETCHER__S3__REGION: "region"
    ##SMART_CONTRACT_VERIFIER__SOLIDITY__FETCHER__S3__ENDPOINT: "endpoint"
    ##SMART_CONTRACT_VERIFIER__SOLIDITY__FETCHER__S3__BUCKET: "bucket"

    SMART_CONTRACT_VERIFIER__SOURCIFY__ENABLED: "true"
    SMART_CONTRACT_VERIFIER__SOURCIFY__API_URL: "https://sourcify.dev/server/"
    SMART_CONTRACT_VERIFIER__SOURCIFY__VERIFICATION_ATTEMPTS: "3"
    SMART_CONTRACT_VERIFIER__SOURCIFY__REQUEST_TIMEOUT: "10"

    SMART_CONTRACT_VERIFIER__METRICS__ENABLED: "true"
    SMART_CONTRACT_VERIFIER__METRICS__ADDR: "0.0.0.0:{{ .Values.scVerifier.portPrometheus }}"
    SMART_CONTRACT_VERIFIER__METRICS__ROUTE: "/metrics"

    SMART_CONTRACT_VERIFIER__JAEGER__ENABLED: "false"
    SMART_CONTRACT_VERIFIER__JAEGER__AGENT_ENDPOINT: "localhost:6831"
```

What's the upgrade steps ?
